name: Verify PR Description

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  verify-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Verify PR description format
        run: |
          description="${{ github.event.pull_request.body }}"
          regex="^SCRUM-[0-9]+ .+$"
          
          if [[ ! "$description" =~ $regex ]]; then
            echo "❌ PR description does not match the required pattern: SCRUM-<number> <message>"
            echo "Invalid description: $description"
            exit 1
          fi
          
          echo "✅ PR description is valid."
